[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nmap-mcp"
version = "0.1.0"
description = "A MCP server for nmap network scanning"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "fastmcp>=2.14.5",
    "python-nmap>=0.7.1"
]

[project.scripts]
nmap-mcp = "nmap_mcp:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
